### ISSUE TITLE
ホームスクリーンから起動時、利用規約のページが404

### ISSUE THREAD

**Issue by kmn** [lcnem/lcnem-wallet#134]
ホームスクリーンからlcnem起動時、ホームスクリーンのページがある404になる。

**Comment by kmn** [comment]
![3e5811df-b313-4004-93d6-05d1a56ff6be](https://user-images.githubusercontent.com/973161/47598248-e813cb80-d9cb-11e8-9a03-cc16c0f13dd3.jpeg)

**Comment by YuKimura45z** [comment]
developブランチにて修正しました！
masterデプロイ時点で修正されます。
