### ISSUE TITLE
スマホ利用時、ダッシュボードの文字が被ってる？

### ISSUE THREAD

**Issue by kmn** [lcnem/lcnem-wallet#135]
![27ec2844-7597-42ae-b3a0-a4de783b4a62](https://user-images.githubusercontent.com/973161/47598288-90299480-d9cc-11e8-9b0d-a50799182adb.jpeg)

**Comment by YuKimura45z** [comment]
![screenshot_20181027-104334](https://user-images.githubusercontent.com/33382781/47598343-6b85ea80-d9d5-11e8-8ba1-240e917d3a18.png)

正常であればmaterialアイコンがレンダリングされます。
考えられる原因としては、通信が遅くてアイコンダウンロードができなかった、とかかと思われます。
