### ISSUE TITLE
コンタクトリストにハイフン無しのアドレスを登録すると表示が崩れてしまう

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/lcnem-wallet#148]
# 解決
* 入力するときにハイフン検知して、あったらハイフン取り除く

**Comment by YuKimura45z** [comment]
いやすでにやってるよそれ…
それやってハイフン無し入力したけっか崩れるってことでしょ…

cssでword wrap設定するしかない

**Comment by YuKimura45z** [comment]
wordwrapというか、アドレス部分をoverflow autoにしたほうがよいか。

**Comment by YuKimura45z** [comment]
家帰ったらやる
