### ISSUE TITLE
ウォレットを削除してもrefreshしないとテーブルの中に残ったまま

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/lcnem-wallet#152]

**Comment by YuKimura45z** [comment]
これ試したけどちゃんとawait refreshしてるし原因がわからないので、みやともさんヘルプ案件か。

**Comment by YuKimura45z** [comment]
ちなみにservice内でobjectのdelete式やってるのでforceなくてもいいはずなんだよね

でforceしてみても案の定解決せず

ブラウザリロードしか対策できない。

**Comment by tomohidemiya** [comment]
多分原因ですが、WalletServiceでウォレット削除する時に、ローカルとクラウドを
同時に削除しようとしているのが原因かとおもいます！

```
export class WalletsService {
  public wallets?: {
    [id: string]: Wallet
  };
  public plan?: Plan;
  public localWallets: {
    [id: string]: string
  } = {};
```
→これってwalletsがクラウド保存のウォレットで、localWalletsがローカル保存のウォレットですよね？
