### ISSUE TITLE
コンタクトも消してもリフレッシュされない？

### ISSUE THREAD

**Issue by YuKimura45z** [lcnem/lcnem-wallet#155]
await refreshしてるにもかかわらず。
これもforce関係ないし、force trueでも解決しなかった。

**Comment by YuKimura45z** [comment]
ありがとうございます！お願いしますー！

**Comment by tomohidemiya** [comment]
これはdeleteロジックにawait付いてなかったので、this.contact.deleteContact とリフレッシュが待ち合わせできてないことが原因でしたー！

**Comment by YuKimura45z** [comment]
ええええ、これ、非同期だったんてすかーーー😨
ありがとうございます！！

**Comment by tomohidemiya** [comment]
あ、誤解与えたかも。。。
delete ロジックと書いたので、delete演算子が非同期っぽい感じに見えますが、
あくまで非同期なのは ContactService の deleteContact です！

なのでコールバック関数の中にasync-awaitつけてあげて解決します！

**Comment by YuKimura45z** [comment]
あーーーー、そういうことですね、理解しました！笑

await忘れの完全な凡ミスでした。。。笑

**Comment by tomohidemiya** [comment]
良かった良かったw
