### ISSUE TITLE
アドレスが表示されると、右下のプラスボタンか表示されなくなる

### ISSUE THREAD

**Issue by kmn** [lcnem/lcnem-wallet#162]
ios iPhone8

**Comment by kmn** [comment]
お手すきで！

**Comment by kmn** [comment]
![5d12016e-c521-40cd-892f-9b247210ed08](https://user-images.githubusercontent.com/973161/48118982-ed64f600-e2a8-11e8-841e-76a5e766ae32.jpeg)

**Comment by YuKimura45z** [comment]
そのページにはもともと右下フローティング○+ボタンがないのですが、アドレスが表示される前は表示されちゃってた感じでしょうか？

**Comment by YuKimura45z** [comment]
あー、それは仕様ですね、、😅
