### ISSUE TITLE
秘密鍵がないときに挙動がおかしい

### ISSUE THREAD

**Issue by Dragon-taro** [lcnem/lcnem-wallet#167]
ローカルで秘密鍵を生成するようにしたときに、秘密鍵インポート前のWalletを開くとクラウドで保存されている方のWalletの中身が表示されてしまう。
おそらく、秘密鍵がないときにエラー処理をしないでもともとの秘密鍵のグローバル変数を参照しているためだと思う。

**Comment by YuKimura45z** [comment]
原因わかった
