### ISSUE TITLE
秘密鍵インポートおかしいかも

### ISSUE THREAD

**Issue by YuKimura45z** [lcnem/lcnem-wallet#172]
だれか至急確認と修正お願いします

**Comment by ryuseikurata** [comment]
クラウド　インポート正常に動作
ローカル　インポート　おk押せても反映されませんでした。リロードしたら反映されました。

**Comment by YuKimura45z** [comment]
ざす
なるほど
原因究明もたのむ

**Comment by ryuseikurata** [comment]
```
public createLocalWallet(id: string, wallet: string) {
    this.localWallets[id] = wallet;
    localStorage.setItem("wallets", JSON.stringify(this.localWallets));
  }
```
ここにrefresh()追加したら早いですね、、、

原因はわからず。というのも、おk押したらなんで反映されるのかがそもそもわからないという、、

**Comment by YuKimura45z** [comment]
原因わからないなかで正しい解決策を言えるわけがないので原因なんとか探しましょう

**Comment by YuKimura45z** [comment]
まあインポートしたらコンポーネント側でリフレッシュってのがたしかにはやいのかも

**Comment by ryuseikurata** [comment]
ローカルインポートしてconsole開いたらこんなの出てきたので、これが原因なのかもしれない。
<img width="470" alt="2018-11-10 17 06 39" src="https://user-images.githubusercontent.com/32031454/48299082-5481e500-e50b-11e8-886e-92f3357600eb.png">

**Comment by YuKimura45z** [comment]
きっとそれやわ
