### ISSUE TITLE
ログイン前に注意書き

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/lcnem-wallet#198]

**Comment by YuKimura45z** [comment]
サイトへのリンクで良いのでは？

**Comment by ryuseikurata** [comment]
冗長じゃないという点ではいいと思うのですが、
不親切じゃないですかね？

**Comment by YuKimura45z** [comment]
どの点がどうなるから不親切まで言ってくれないと話進められない

**Comment by ryuseikurata** [comment]
Walletのサービスを使おうとしているユーザーが、
わざわざCorporateサイトに飛ばないと注意書きが見れないという点が不親切かなと。

**Comment by YuKimura45z** [comment]
動線が増えるということね？

**Comment by YuKimura45z** [comment]
要約力、、、

**Comment by YuKimura45z** [comment]
動線はあまり増えないとおもう

初めて使う人はそもそもサイト→ウォレットくるから

ウォレットに注意書き書くのはあくまでバックアップ的であって
リンクで十分だと思う

**Comment by YuKimura45z** [comment]
iosアプリならそういう流れになるけどこれはwebアプリなのでそういう流れでなくてもよいのでは。
というかwebアプリやとマーケットプレイスがないのでそういう流れキツくないか。

**Comment by ryuseikurata** [comment]
> webアプリだからそういう流れでいい

ここわかりませんでした。
サービスがあって、運営会社気になって、コーポレートサイトとぶは、web ,iOS関係なく自然では？


> マーケットプレイスがないのでそういう流れキツい

同意です

**Comment by YuKimura45z** [comment]
マーケットプレイスが無いからiOSほどそれが支配的な流れになれないじゃん

冗長にするよりリンク貼るで当面はしのげるやろ
いま冗長にするのは合理的でない（将来は知らん

**Comment by ryuseikurata** [comment]
> マーケットプレイスが無いからiOSほどそれが支配的な流れになれないじゃん

だからってweb が ` サービスがあって、運営会社気になって、コーポレートサイトとぶ ` でないとなりますか？

確かに。現時点は合理的でない気がしてきました。

**Comment by YuKimura45z** [comment]
あるかないかの2択をいってるんじゃない
