### ISSUE TITLE
transfer 宛先のautoCompleteいらない説、もしくは改善あり。

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/lcnem-wallet#22]
宛先、Userが保持している、アドレスならばわかりますが、入力したものがそのまま反映されるのはいらないと思います。
やるならば、
Userのアドレス帳を作って、宛先をhoverしたら、保持してるアドレスが一覧として出てくるみたいな方がいいと思いました。
<img width="1410" alt="2018-09-09 1 28 40" src="https://user-images.githubusercontent.com/32031454/45256346-292a2f00-b3d0-11e8-892a-396fa60be9ed.png">

**Comment by YuKimura45z** [comment]
ネームスペースエイリアスを解決する、より良いUIの案があるのであれば賛成
そのより良い案がほしい

**Comment by YuKimura45z** [comment]
アドレス帳はすぐにつくれないとおもうので

**Comment by YuKimura45z** [comment]
そもそもとしてNEM NIS APIはすべてバックエンドで叩き、フロントはウォレットの専用API叩くだけにするのもあり
そういう設計ならアドレス帳とかへの拡張がしやすそう

**Comment by YuKimura45z** [comment]
もうアドレス帳つくっちまおう
