### ISSUE TITLE
アドレスはコピペできるようにしたほうがいい

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/lcnem-wallet#23]
[これでできそう](https://qiita.com/inouet/items/26b93c5f5f4b65c05e00)

**Comment by YuKimura45z** [comment]
あまりjsライブラリを足してくことを考えるべきではないと思う

**Comment by ryuseikurata** [comment]
ライブラリ以外のやり方がわからなかったです。

**Comment by ryuseikurata** [comment]
https://stackoverflow.com/questions/49102724/angular-5-copy-to-clipboard

**Comment by ryuseikurata** [comment]
あった！
