### ISSUE TITLE
議論あり 広告非表示機能がStandardかPremiumか

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/lcnem-wallet#247]
**議論あり 広告非表示機能がStandardかPremiumか**
* 仮説だが、広告非表示、Standardでやった方が利益あがる説。
皆様のご意見を聞きたいです。

![ios 9](https://user-images.githubusercontent.com/32031454/51046133-a37df080-1608-11e9-8856-c617860f73a2.jpg)

**Comment by YuKimura45z** [comment]
slack内議論のとおりですのでとじます
