### ISSUE TITLE
ウォレット作成時

### ISSUE THREAD

**Issue by YuKimura45z** [lcnem/lcnem-wallet#249]
ウォレット作成時に、クラウドを選択していて、それが二つ目でかつ無料プランのであれば忠告を表示すべきだろう

**Comment by ThetaShis** [comment]
クラウドウォレットをすでに一つもっていて、
wallet.create.dialogで新規ウォレットを追加する時に、
クラウドの選択ボタンを押せばcheckWalletメソッドを呼び出します。

checkWalletメソッドはwallets.componentにあり、
クラウドウォレット二つ目を希望している人がFreeプランの場合に注意喚起を呼び出す。

と言う設計です。

**Comment by YuKimura45z** [comment]
componentのDIはできないので、ダイアログのコンポーネントでもwalletサービス活用してチェックするメソッド作る必要がありますね

**Comment by ThetaShis** [comment]
うわあああああ
それ最初やってた。。。
サービスだけやもんなDIは。
Walletサービスの他のメソッドを見てなぜか遠慮した。

**Comment by YuKimura45z** [comment]
進んでいるので、閉じます！
