### ISSUE TITLE
Walletの使用説明htmlを作成

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/lcnem-wallet#25]

**Comment by YuKimura45z** [comment]
htmlというより、アニメーションでチュートリアル？つけるといいかもな

初回起動かどうかはfirebaseではなくブラウザのstorageつかって保管しといて

**Comment by YuKimura45z** [comment]
gmailの新デザイン切り変え時のとか、
スプレッドシートの新機能追加時みたいなああいう上下左右0のfixedのポップアップで良いと思う（伝われ）

**Comment by ryuseikurata** [comment]
・初回起動時にのみモーダル起動（localStorageにstartCount: 0を最初にもたせて、startCountが0の場合に、モーダルを起動させる。起動させかつ、startCount:0 だった場合に、setItemで、startCount:1にする）
## アニメーション
・popup/daialogを使って表示
・どのスライドにもわかりやすさのため、画像をはる（自前で作るか
作らないかは置いといて）
## 説明するべきところ
・送信機能（初心者向け）
・StableCoinの説明（入金、出金）
・Walletの安全性

### 送信機能
**Image画像**
QRをスマホカメラでScanして自分のアドレスから、他者のアドレスに、アセットが移動する様子
**文言**
・「アセットを他の人に簡単に送ることができます」

### StableCoinの説明
**Image画像**
日本円とlc:jpy, ドルとlc:enが同じ価格と想起させ、それをWallet内で交換できることが伝わるイメージ
**文言**
・「各国の法定通貨と同価格で買うことができます。また、AmazonCardと交換することもできます。現在、ドルと日本円に対応しています。」

## Walletの安全性
**Image画像**
ユーザーがもつ秘密鍵が暗号化されていることを想起させるイメージ
**文言**
「お客様の秘密鍵は当社が保管しております。尚、保管の際には、秘密鍵を暗号化しております。」

**Comment by YuKimura45z** [comment]
・startCount変数、なぜnumberにするのか。
初回起動かどうか判断するなら
`initialized: boolean`
でいいはずだ

・popup/daialogてなに？

・lc:enってなんなのか意味不明

・ドルについて話ついてこれてないぞ

・秘密鍵の説明はむしろしないでいいと思う（気にせず使ってほしい）

**Comment by ryuseikurata** [comment]
> ・startCount変数、なぜnumberにするのか。
初回起動かどうか判断するなら
initialized: boolean
でいいはずだ

なるほど

> popup/daialogてなに？
AngularMaterialのDialogのことです。

> 秘密鍵の説明はむしろしないでいいと思う（気にせず使ってほしい）
了解です。

**Comment by YuKimura45z** [comment]
UI大幅改善したおかげで、不要説でてきた
