### ISSUE TITLE
pages/home/nem/faucet

### ISSUE THREAD

**Issue by YuKimura45z** [lcnem/lcnem-wallet#263]
残高1xem未満であれば1xem付与するAPIを
- firebase functionsにおけるfaucet API
- api.service faucetメソッド
にて実装済み

それらを確認してから、
pages/home/nem/faucetコンポーネントをつくってほしい

**表示ロジック**
* 無料プランだったら、<app-faucet>表示かつボタン押せない（有料プランへの訴求効果）
=> isPlan == free 
* 有料プランかつ1xem未満だったら<app-faucet>表示かつボタン押す
=> isPlan != free && amount << 1
* 有料プランかつ1xem以上だったら<app-faucet>非表示(1xem以上だったらそもそも無駄な表示であるため）

**Comment by YuKimura45z** [comment]
シュレックやってみますかあ

**Comment by ryuseikurata** [comment]
はい
