### ISSUE TITLE
history From TOは議論あり

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/lcnem-wallet#27]
<img width="264" alt="2018-09-09 1 41 13" src="https://user-images.githubusercontent.com/32031454/45256437-74910d00-b3d1-11e8-88df-9b7b6a745dd7.png">
できればエイリアスをつけたい。
Nanowalletと同じ仕様にしているが、
ぶっちゃけ送信の場合、From,受信の場合、Toは自分のアドレスと決まっているので、
あなたとか表記もっとわかりやすくしてもいいのではないか。

**Comment by YuKimura45z** [comment]
アドレス帳を実装し、逆探知する感じで良いと思われる

まずはアドレス帳ですわ
