### ISSUE TITLE
入出金のボタンがわかりにくい

### ISSUE THREAD

**Issue by Dragon-taro** [lcnem/lcnem-wallet#270]
hoverでアクションでも入れんとボタンには見えない。
ここやってたシュレックにやってもらいたい

**Comment by YuKimura45z** [comment]
あと、APIのほうではdepositをorder-cheque
withdrawをorder-cashと命名変更しましたので、フロントも名前変更しよか

**Comment by Dragon-taro** [comment]
そっちの方が確かにわかりやすい
