### ISSUE TITLE
連携のログイン周り

### ISSUE THREAD

**Issue by Dragon-taro** [lcnem/lcnem-wallet#272]
1. ログインのリダイレクトで済ませる
- 追加のコードを書く必要がないから楽
- ux的には微妙

2. 連携画面にログインしてなかったらログインボタンを表示
- 面倒だがわかりやすい
- routerの部分も変える必要ありそう

**Comment by YuKimura45z** [comment]
ログインボタンやってもウォレット選択までさせないといけないからそこんところめんどいんよね…。
redirectとclientTokenがクエリに含まれている状態で任意の場所に遷移するとintegrateにとぶ、としとけば丸く収まるのではという気がする
