### ISSUE TITLE
pages/account/integrate

### ISSUE THREAD

**Issue by YuKimura45z** [lcnem/lcnem-wallet#274]
>連携ページにoauthみたいに何がどうなるのかの説明を書いといた方がいいかと思いました。
WLTFileが書き出されて外部のサービスでwalletが使えるようになりますとかパスワードが何なのかとか

**Comment by YuKimura45z** [comment]
シュレックかたけるさんでお願いします

**Comment by YuKimura45z** [comment]
pタグにtranslation変数で書くだけなので所要時間2分ですね
技術的難易度は屁

**Comment by ryuseikurata** [comment]
やります

**Comment by ryuseikurata** [comment]
すみません。連携ページてどこでしたっけ
