### ISSUE TITLE
サードパーティ秘密鍵共有機能

### ISSUE THREAD

**Issue by YuKimura45z** [lcnem/lcnem-wallet#284]
デバッグ誰か

**Comment by ryuseikurata** [comment]
# PC
* 成功
# iOS
* カメラが起動しない

**Comment by YuKimura45z** [comment]
メッセージとかアドレスとか全部いれてみた？

**Comment by YuKimura45z** [comment]
ごめんやっぱなんでもない

**Comment by ryuseikurata** [comment]
**内容**
* 全部入れたけどボタンが押下できない。(クリックできない)
<img width="1440" alt="2019-02-09 20 01 36" src="https://user-images.githubusercontent.com/32031454/52519878-8854de00-2ca5-11e9-8303-930386e20b0f.png">
