### ISSUE TITLE
iosログインすると１回目でログイン失敗となり、２回目で成功するも、flashはfailedになることがある

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/lcnem-wallet#285]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by YuKimura45z** [comment]
flashってなんどすか

**Comment by ryuseikurata** [comment]
発生確率低いので(1回しか出なかった。)一旦closeします
