### ISSUE TITLE
contacts, addressによって画面崩れ起きている

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/lcnem-wallet#286]
**Describe the bug**
contacts, addressによって画面崩れ起きている

**Screenshots**
![file 1](https://user-images.githubusercontent.com/32031454/52519933-8c353000-2ca6-11e9-8853-d85f386698fc.jpg)

**Smartphone (please complete the following information):**
 - ios5s

**Comment by YuKimura45z** [comment]
修正法、任せます

**Comment by Dragon-taro** [comment]
```
overflow: hidden;

or

overflow: auto;
```
で良さそう
