### ISSUE TITLE
せっかく会社のアイコンを表示しているのならば、コーポレートサイトのリンク貼ってもいいかも

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/lcnem-wallet#32]
-
<img width="302" alt="2018-09-10 2 08 47" src="https://user-images.githubusercontent.com/32031454/45266965-986e5480-b49e-11e8-93ca-8f3bfaac2a2b.png">

**Comment by YuKimura45z** [comment]
ドロワーにいれよう
