### ISSUE TITLE
現LCNEM walletから次バージョンwalletへの移行の通知

### ISSUE THREAD

**Issue by yutaro-elk** [lcnem/lcnem-wallet#322]
資金決済法の施行が2020年4月予定だとされる。
それまでには現LCNEMwalletからの移行が必要。

# 理由
現在は秘密鍵をLCNEMが関与できる状態だから。

# 通知内容
## 次バージョンがロンチしている場合
* 移行はユーザーにやってもらうか
* LCNEM側で自動で移行できるか

## 次バージョンがロンチしていない場合
* 資金の引出しのお願い
* 期限はいつにするか

## 
Catapultのメインネットロンチに合わせ、移行できると一番良いかと

**Comment by YuKimura45z** [comment]
おそらく秘密鍵へのパスワード暗号化を義務付けるUIにしておけばユーザーに移行を促さなくても適法にいけそう…？
初回アクセス時にあなたのパスワードとしてUIDみせればよさげ

**Comment by yutaro-elk** [comment]
その場合でもLCNEMがUIDを分かっていて、そこから秘密鍵を導出できる以上、交換業とらないと違法になるのかなという理解なんですがいかがでしょう…？

**Comment by YuKimura45z** [comment]
パスワードをいつでも変えられるのであれば言い逃れできるんじゃないかなと！
その時点でUIDが必ずパスワードであるというのが崩れるのでｗ

**Comment by yutaro-elk** [comment]
MTの時に行けそうな感じがしたので一回閉じます
