### ISSUE TITLE
アイコン、Angularじゃなくて、lcnemにしたい。

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/lcnem-wallet#33]
<img width="229" alt="2018-09-10 2 10 11" src="https://user-images.githubusercontent.com/32031454/45266970-b50a8c80-b49e-11e8-9ec0-fb6cbc3800c8.png">

**Comment by YuKimura45z** [comment]
それキャッシュ残ってるだけやろｗｗｗ
