### ISSUE TITLE
日本語版でウォレットの残高に最初に表示される言語を日本語にする

### ISSUE THREAD

**Issue by jeijeijei777** [lcnem/lcnem-wallet#342]
## 目的
LCNEM Walletの日本語バージョンで「ウォレット画面に表示される残高の通貨単位」がUSDになっている部分を日本円に変更する

## TaskList
+ [通貨単位を日本円にする ] 

## Doneの定義
JPYが日本語版のウォレット残高に表示されること

**Comment by YuKimura45z** [comment]
極端な解釈をするとエスノセントリズムというか、JPYが全世界で初期値ないといけない理由を考えるといいかもしれません（おそらくない）。
やるべきは固定初期値を変えることではなく、javascriptでブラウザの言語情報取得をlanguage.service.tsがしているように、ブラウザの言語情報のja-JP（ISO言語コード）のハイフン後（言語名-国名の構造になっている）を取得して判別したほうがいいんじゃないでしょうか。

**Comment by jeijeijei777** [comment]
言語コードの変更に合わせてその国の通貨に変更されるように考えていました！
全世界でJPYを初期値にしようとかではなく、あくまでも言語コードがjaの時にそれに紐づけてJPYが初期表示されるようになったらいいと思いました。同様にenならUSDが初期表示されるようになっています

**Comment by YuKimura45z** [comment]
すみません、でしたら問題ありません！

**Comment by jeijeijei777** [comment]
いえ、ありがとうございます！
