### ISSUE TITLE
hoverしたら各項目の説明つけた方がいいかもしれない

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/lcnem-wallet#36]
<img width="227" alt="2018-09-10 2 14 31" src="https://user-images.githubusercontent.com/32031454/45266999-44b03b00-b49f-11e8-92be-06351d57a706.png">

**Comment by YuKimura45z** [comment]
mouseleaveてなんすか？？？
matTooltipでは

**Comment by ryuseikurata** [comment]
homeのmav-nave-listそれぞれに、
matToolTipを入れて、説明を入れる。
