### ISSUE TITLE
Contacts book is needed

### ISSUE THREAD

**Issue by YuKimura45z** [lcnem/lcnem-wallet#59]
まずfirebase firestoreに
profiles/{userId}/
```
{
  name: string;
  nem: string;
  cosmos: string;
}
```
をつくって、
users/user/contacts/{uid}
には、コンタクト対象のユーザーidを空オブジェクトで入れておく。

一覧表示したいときはusers/user/contacts/{uid}のうち好きな件数を取得し、それぞれprofiles/{userId}
```
{
  name: string;
  nem: string;
  cosmos: string;
}
```
を参照すればよいことになる

**Comment by ryuseikurata** [comment]
#68
