### ISSUE TITLE
New History UI 

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/lcnem-wallet#67]
# 仕様
<img width="460" alt="2018-09-22 9 37 26" src="https://user-images.githubusercontent.com/32031454/45911178-22c59980-be4b-11e8-9f0c-89783693ca01.png">

* mat-card-avatarには、アドレス帳機能によって実装される画像を将来的に使う
* mat-card-headerに、
〜〜からの受信/送信表記
* mat-card-subheaderに、日付表示
* そしてその下に漫画の吹き出しのような感じでmat-card-avatarからコメントがでてきてる
*その下にはアセット表記
* そして右下にmat-iconでdoneアイコンか、処理中のアイコンおく。
* それにはmatTooltipで完了もしくはブロックチェーン内処理中をだす
* 名前もGoogleでとる。（クリックしたら、アドレスが出るようにする）

 # 機能追加の背景
- [ ] #27 #28 これをやらずに、抜本的な改変が必要
- [ ] Google認証の特徴を活かす
- [ ] メッセージを見やすいUIにする
- [ ] UXの向上・継続的な使用を促す

# 担当
* 倉田

# 課題・現状
* まだ、合意形成されていない。
* これが一番とは限らない。

**Comment by ryuseikurata** [comment]
> mat-card-avatarには、アドレス帳機能によって実装される画像を将来的に使う
初期画像の人のイニシャルになる可能性があってそれはダサい。
なので、NanoWalletのように、
自分に向いてる送信とか、向こうに向いてる送信とか、そういうアイコンをmat-card-avatarにおけばいい

**Comment by YuKimura45z** [comment]
done
