### ISSUE TITLE
利用規約を新しいのにさしかえ

### ISSUE THREAD

**Issue by YuKimura45z** [lcnem/lcnem-wallet#69]
まだできてなかった
英訳も含めてやっておいたほうがよい。

**Comment by ryuseikurata** [comment]
英語の翻訳は出来てましたっけ？

**Comment by YuKimura45z** [comment]
たけるさん待ち
といっても利用規約英訳は絶対しんどいのでまず日本語からやってもよさそうだな

俺がついでに日本語だけやっておく

**Comment by ryuseikurata** [comment]
一回弁護士にレビューしてもらうのありかも

**Comment by YuKimura45z** [comment]
は？

**Comment by ryuseikurata** [comment]
把握してませんでした。すみません。

**Comment by ryuseikurata** [comment]
- [ ] @ThetaShis が英訳を作る
- [ ] @YuKimura45z が日本語を作る
- [ ]

**Comment by YuKimura45z** [comment]
いや、、だからよ、、日本語はもう弁護士がつくったんやって、、

**Comment by YuKimura45z** [comment]
日本語だけやっておくというのは差し替えをやっておくという意味ね、、
ちなみにまだやってない、、

**Comment by YuKimura45z** [comment]
日本語、やはりassigneeにまかせます
