### ISSUE TITLE
ユーザーがステーブルコインを認知させる機能

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/lcnem-wallet#80]
概要
> 先行優位性持てるのは今しかないと思うんですよね。なので、時間をこっちにもうちょっと割くというより、何かview数を稼げるような機能を設けたいというのはあります。

**Comment by ryuseikurata** [comment]
# 具体例
* SNS拡散機能（Twitterで拡散したら、QRコードが見える）

**Comment by YuKimura45z** [comment]
なんのqrなのかが全くわからないんだが

**Comment by YuKimura45z** [comment]
マジで不透明すぎるｗｗｗ
もうちょい説明してw
・QRコードの内容は何？
・ユーザーが認知させる？主語がわからない

**Comment by ryuseikurata** [comment]
もっと具体化すると、
アドレス帳の自分のアドレス欄の右にTwitterシェアボタンをつけて、押したら、
自動的に自分のアドレスのQRと、「LCNEMで、仮想通貨を使ってみよう！！」見たいなdescriptionを合わせて投稿準備される。

**Comment by YuKimura45z** [comment]
うーんせやからOGPにQRはくにあつさんの言う通り効果薄いんよね。

**Comment by YuKimura45z** [comment]
あ、OGP設定は必要やな
issueあげます
