### ISSUE TITLE
AngularMaterial

### ISSUE THREAD

**Issue by YuKimura45z** [lcnem/lcnem-wallet#82]
AngularMaterialは工数削減にも生産性向上にも寄与するため、不可欠。
しかしAngularMaterialそのままだと蛋白になりがちなので、ボタンとかカードとかに関してはcssとか公式で提供されるプロパティとかで少しずつ修正していく。

↑UIはこういう方針で行くのが、工数コスパのバランス良いかなと

**Comment by YuKimura45z** [comment]
このIssueでは、このmaterialコンポーネントはこう調整したほうが良くね？みたいなのを出していきたい

おれは、mat-cardを使うのであれば角丸半径上げるべきと思う
あと、ボタンも完全に角丸みたいな感じもいいとおもう（直径=短辺となるような）

**Comment by ryuseikurata** [comment]
issueの使い方それだと効率悪いかと。
issueはあくまでその機能のみで、議論するところは機能ごとにやるべきだと思います。
なので、やるとしたら、AngularMaterialというLabelつけて、AngularMaterialのことを指しているissueだということを示しつつ、部分ごとにやるべきかと。
