### ISSUE TITLE
送信画面に説明

### ISSUE THREAD

**Issue by YuKimura45z** [lcnem/lcnem-wallet#86]
送信画面でも、ブロックチェーンのルールなど基礎的なことでも説明を充実したほうがよい。
・ブロックチェーンは不可逆的
・手数料に仮想通貨が必要

**Comment by ryuseikurata** [comment]
#25

**Comment by ryuseikurata** [comment]
・送信画面にはリンクを貼って、別で説明ページを設けたほうがいいかもしれません
・メリットとQ&Aを載せていく。

**Comment by YuKimura45z** [comment]
説明ページなんてダルくて読みたがらないんじゃないかな？
情報必要最小限に絞って、嫌でも目にとまるところにおいておく必要が、リテラシ低いユーザー向けにありそう。
