### ISSUE TITLE
入金説明をわかりやすくする

### ISSUE THREAD

**Issue by ryuseikurata** [lcnem/lcnem-wallet#87]
- [ ] topの入金にhoverつけて説明
- [ ] 中に行くと詳細な説明(法定通貨と同じ値段で買うことができる的な説明は必要な気が）
- [ ] 詳細- アドレスhover　「このアドレスにlc:jpyが送られます。」
- [ ] 詳細- 通貨 「購入するステーブルコインを選びます」
- [ ] 詳細 - 金額 「購入する金額（支払う金額）を決めます」
- [ ] 詳細 - 表記なのですが、方法じゃなくてお支払い方法の方がいいかも
- [ ] 詳細 - 支払い 「支払い方法を選択できます。（現在はPaypalのみです）

**Comment by YuKimura45z** [comment]
なあ、なんで新トピつくるのよ、、、
#84 あるやないか、、
