### ISSUE TITLE
変数名mosaicをassetに変更

### ISSUE THREAD

**Issue by YuKimura45z** [lcnem/lcnem-wallet#90]
nem-library2.0.0から、mosaicというネーミングは全廃され、assetにかわりました

しかし当ソースにはmosaicそのものもしくはmosaicをつかった変数名が多々あります

それら変数をライブラリに従ってassetと改名したほうが読みやすいと思う

**Comment by kuniatsu** [comment]
ざっくりgrepかけてみたら約150か所、名前の変更なので大丈夫だとは思いますけど、結構な影響範囲ともいえますね。

**Comment by YuKimura45z** [comment]
完了しましたｗ
おもったよりはやかったですｗ
