### ISSUE TITLE
サイドメニューのヘッダー部分のデザイン

### ISSUE THREAD

**Issue by kuniatsu** [lcnem/lcnem-wallet#91]
サイドメニュー内の上部にLCNEMとGoogleのユーザアイコンが表示され、マウスポインタの変更（css:cursorの変更）がされるのですが、これは意図があるわけでないなら変更してはいかがでしょうか？

![default](https://user-images.githubusercontent.com/11168889/46365839-902bc280-c6b4-11e8-8147-eba83acd2fbb.PNG)

**Comment by YuKimura45z** [comment]
toolbarに収まる丸にするために、mat-icon-buttonとして作っているので、htmlの変更ではなく、css側で
cursor: xxx
を指定して、なおしましょう！

**Comment by YuKimura45z** [comment]
done
